import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillTwitterCircle, AiFillLinkedin } from "react-icons/ai";
import { RiWhatsappFill } from "react-icons/ri";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Tubolayefa | Portfolio </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:20 lg:40 dark:bg-gray-900">
        <section className="min-h-screen ">
          <nav className="pt-8 flex justify-between ">
            <h1 className="font-burtons text-xl dark:text-white">
              Developedbyed
            </h1>
            <ul className="flex items-center justify-around">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-br from-cyan-700 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="lg:flex lg:items-center lg:justify-between">
            <div className="text-center p-10 lg:text-left ">
              <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl ">
                Tubolayefa
              </h2>
              <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
                Developer and Designer
              </h3>
              <p className="text-2xl py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
                Freelancer providing services for programming and design content
                needs. Join me down below and let us get carcking!
              </p>
              <div className="text-4xl flex justify-center gap-16 text-gray-600 dark:text-white lg:justify-start lg:gap-8 ">
                <AiFillTwitterCircle className="" />
                <AiFillLinkedin />
                <RiWhatsappFill />
              </div>
            </div>
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full text-center w-60 h-60 mt-10 overflow-hidden md:w-96 md:h-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        <section className="mt-10">
          <div className="flex flex-col justify-center items-center lg:px-20 ">
            <h3 className="text-3xl py-5 text-center dark:text-white">
              Services I Offer
            </h3>
            <div>
              <p className="text-2xl py-3 leading-8 text-gray-800   dark:text-white">
                Since the beginning of my journey as a freelance designer and
                developer, I have done remote work for{" "}
                <span className="text-teal-500">agencies</span> consulted for
                <span className="text-teal-500"> startups</span> and
                collaborated with talented people to create digital products for
                both business and consumer use.
              </p>
              <p className="text-2xl py-5 leading-8 text-gray-800 dark:text-white">
                I offer from a wide range of services, including brand design,
                programming and teaching.
              </p>
            </div>
          </div>

          <div className="md:flex   gap-2 lg:px-20 w-100  ">
            <div className="flex flex-col items-center text-center shadow-lg p-10 rounded-xl my-10 ">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Beautiful Designs
              </h3>
              <p className="py-2 dark:text-white">
                Creating elegant designs suited for your needs and following
                core design theory.
              </p>
              <h4 className="py-4 text-teal-600 ">Design tools I use</h4>
              <p className="text-gray-800 py-1 dark:text-white">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-white">Figma</p>
              <p className="text-gray-800 py-1 dark:text-white">Illustrator</p>
            </div>
            <div className="flex flex-col items-center text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white ">
                Beautiful Designs
              </h3>
              <p className="py-2 dark:text-white">
                Creating elegant designs suited for your needs and following
                core design theory.
              </p>
              <h4 className="py-4 text-teal-600 dark:text-white">
                Design tools I use
              </h4>
              <p className="text-gray-800 py-1 dark:text-white">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-white">Figma</p>
              <p className="text-gray-800 py-1 dark:text-white">Illustrator</p>
            </div>
            <div className="flex flex-col items-center text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  dark:text-white">
                Beautiful Designs
              </h3>
              <p className="py-2 dark:text-white">
                Creating elegant designs suited for your needs and following
                core design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1 dark:text-white">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-white">Figma</p>
              <p className="text-gray-800 py-1 dark:text-white">Illustrator</p>
            </div>
          </div>
        </section>

        <section>
          <div className="lg:px-20">
            <h3 className="text-3xl py-5 text-center dark:text-white">
              Portfolio
            </h3>
            <p className="text-2xl py-5 leading-8 text-gray-800 dark:text-white">
              Since the beginning of my journey as a freelance designer and
              developer, I have done remote work for{" "}
              <span className="text-teal-500">agencies</span> consulted for
              <span className="text-teal-500"> startups</span> and collaborated
              with talented people to create digital products for both business
              and consumer use.
            </p>
            <p className="text-2xl py-5 leading-8 text-gray-800 dark:text-white">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:px-20 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
